version: '3'
services:
  docker-hub:
    image: defreitas/lubuntu-desktop-tightvncserver:debian-9_2
    hostname: vm.docker
    ports:
      - 5901:5901

  source:
    build: ./
    hostname: vm.docker
    deploy:
      resources:
        limits:
          memory: 300m
    ports:
      - 5901:5901
    environment:
      - RESOLUTION=1024x768
    network_mode: bridge